{% set name = "pytest-check-meta" %}
{% set version = "2.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/pytest-check/pytest_check-{{ version }}.tar.gz
  sha256: 4de76a794a0b504550cce85cfcd6d7bba9c4b99ba2172ef56867c98122518ae3

build:
  number: 0

outputs:
  - name: pytest-check

    build:
      noarch: python
      script: ${PYTHON} -m pip install . -vv --no-deps --no-build-isolation

    requirements:
      host:
        - python >=3.8
        - flit-core >=3.2,<4
        - pip
      run:
        - python >=3.8
        - pytest

    test:
      imports:
        - pytest_check
      requires:
        - pip
      source_files:
        - tests/
        - examples/
        - tox.ini
      commands:
        - pip check
        - pytest -k "not test_max_tb"

  - name: pytest_check

    # Meta-package to the main package, that just installs it
    # it is here to keep-up with the legacy name, containing an
    # underscore ("_") instead of a dash.
    build:
      noarch: generic

    requirements:
      host:
        - python >=3.8
      run:
        - python >=3.8
        - {{ pin_subpackage("pytest-check", exact=True) }}

    test:
      imports:
        - pytest_check

about:
  home: https://github.com/okken/pytest-check
  summary: A pytest plugin that allows multiple failures per test.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
    - bskinn
    - anjos
